package com.example.trabajowordle;

import com.example.conexion.Conector;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class Wordle extends Application {
    @Override
    public void start(Stage stage) throws IOException {
        FXMLLoader fxmlLoader = new FXMLLoader(Wordle.class.getResource("wordle.fxml"));
        Scene scene = new Scene(fxmlLoader.load(), 320, 240);
        stage.setTitle("Hello!");
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        String datos = "TUNTA TUPAN TUPAS TUPEN TUPES TUPIA TUPID TUPIN TUPIO TUPIR TUPIS TUPOS TURAR TURBA TURBE TURBO TURCA TURCO TURMA TURNA TURNE TURNO TURON TURRA TURRE TURRO TUSAD TUSAN TUSAR TUSAS TUSCA TUSCO TUSEN TUSES TUSON TUSOS TUTAS TUTEA TUTEE TUTEO TUTES TUTIA TUTOR TUTOS TUTUS TUYAS TUYOS TUZAS UBICA UBICO UBIES UBIOS UBRES UCASE UCHUS UEBOS UFANA UFANE UFANO UGRES UJIER UJULE ULAGA ULALA ULANO ULEMA ULPOS ULTRA ULUAS ULULA ULULE ULULO UMBRA UMBRO UMERO UNAIS UNCEN UNCES UNCIA UNCID UNCIO UNCIR UNCIS UNGEN UNGES UNGIA UNGID UNGIO UNGIR UNGIS UNIAN UNIAS UNICA UNICO UNIDA UNIDO UNION UNIRA UNIRE UNJAN UNJAS UNTAD UNTAN UNTAR UNTAS UNTEN UNTES UNTOS UNZAN UNZAS UÑADA UÑADO UÑAIS UÑATE UÑERA UÑERE UÑERO UÑESE UÑETA UÑIAN UÑIAS UÑIDA UÑIDO UÑIRA UÑIRE UÑOSA UÑOSO UÑUDO UPABA UPADA UPADO UPAIS UPARA UPARE UPASE UPEIS UPUPA URAOS URAPE URATO URBES URCAS URCES URDAN URDAS URDEN URDES URDIA URDID URDIO URDIR URDIS URDUS UREAS URGEN URGES URGIA URGID URGIO URGIR URGIS URICA URICO URJAN URJAS URNAS URTAS URUBU URUCU URUGA USABA USADA USADO USAIS USAJE USARA USARE USASE USEIS USGOS USIAS USIER USINA USTED USUAL USURA USURE USURO UTERO UVADA UVATE UVEAS UVERA UVERO UVIAR UVULA VACAD VACAN VACAR VACAS VACIA VACIE VACIO VACOS VACUA VACUO VADEA VADEE VADEO VADES VADOS VAFEA VAFEE VAFEO VAGAD VAGAN VAGAR VAGAS VAGON VAGOS VAGUE VAHAD VAHAN VAHAR VAHAS VAHEA VAHEE VAHEN VAHEO VAHES VAHOS VAIDA VAINA VAJEA VAJEE VAJEO VALAR VALED VALEN VALER VALES VALET VALGA VALGO VALIA VALIO VALIS VALLA VALLE VALLO VALON VALOR VALSA VALSE VALSO VALUA VALUE VALUO VALVA VAMOS VANAS VANEA VANEE VANEO VANOS VAPOR VAQUE VARAD VARAL VARAN VARAR VARAS VAREA VAREE VAREN VAREO VARES VARGA VARIA VARIE VARIO VARIS VARIZ VARON VASAR VASAS VASCA VASCO VASOS VASTA VASTO VATER VATES VATIO VAYAN VAYAS VEAIS VECEN VECES VEDAD VEDAN VEDAR VEDAS VEDEN VEDES VEGAS VEIAN VEIAS VEJAD VEJAN VEJAR VEJAS VEJEN VEJES VEJEZ VELAD VELAN VELAR VELAS VELAY VELEN VELES VELIS VELIZ VELLO VELON VELOS VELOZ VEMOS VENAL VENAS VENCE VENCI VENDA VENDE VENDI VENDO VENGA VENGO VENIA VENID VENIR VENIS VENTA VENTE VENTO VENUS VENZA VENZO VERAN VERAS VERAZ VERBA VERBO VERDE VERES VERGA VERGE VERIA VERIL VERJA VERME VERMU VEROS VERSA VERSE VERSO VERTE VERTI VESTE VESTI VETAD VETAN VETAR VETAS VETEA VETEE VETEN VETEO VETES VETON VETOS VEZAD VEZAN VEZAR VEZAS VIADA VIAJA VIAJE VIAJO VIBRA VIBRE VIBRO VICHA VICHE VICHO VICHY VICIA VICIE VICIO VICOS VICTO VIDAS VIDEO VIDES VIDON VIDRO VIEJA VIEJO VIENE VIERA VIERE VIESA VIESE VIGAS VIGIA VIGIE VIGIO VIGOR VILES VILLA VILOS VIMOS VINAL VINAR VINCA VINCO VINOS VINTA VIÑAS VIOLA VIOLE VIOLO VIRAD VIRAL VIRAN VIRAR VIRAS VIREN VIREO VIRES VIRGO VIRIL VIRIO VIROL VIRON VIRUS VISAD VISAN VISAR VISAS VISCO VISEA VISEE VISEN VISEO VISES VISIR VISON VISOR VISOS VISTA VISTE VISTO VITAD VITAL VITAN VITAR VITAS VITEN VITES VITOR VITOS VITRE VIUDA VIUDO VIVAC VIVAD VIVAN VIVAR VIVAS VIVAZ VIVEN VIVES VIVEZ VIVIA VIVID VIVIO VIVIR VIVIS VIVON VIVOS VOACE VOCAL VOCEA VOCEE VOCEO VOCES VODCA VODUS VOILA VOLAD VOLAR VOLAS VOLCA VOLCO VOLEA VOLEE VOLEO VOLON VOLTS VOLVE VOLVI VOLVO VOMER VORAZ VOSEA VOSEE VOSEO VOTAD VOTAN VOTAR VOTAS VOTEN VOTES VOTOS VOTRI VOZNA VOZNE VOZNO VUDUS VUELA VUELE VUELO VUESA VUESO VULGO VULTO VULVA VUSCO XECAS XENON XINCA XIOTE XOLAS XOLOS YABAS YACAL YACAS YACED YACEN YACER YACES YACIA YACIO YACON YAGAN YAGAS YAGUA YAITI YALES YAMAO YAMBO YAMPA YANAS YANTA YANTE YANTO YAPAD YAPAN YAPAR YAPAS YAPEN YAPES YAPUS YAQUE YAQUI YARDA YARES YAREY YAROS YATAI YATAY YATES YAYAS YAYOS YAZCA YAZCO YAZGA YAZGO YEBOS YECOS YEDGO YEDRA YEGUA YELGO YELMO YEMAS YENDO YENES YENTE YERAL YERBA YERGA YERGO YERMA YERME YERMO YERNA YERNO YEROS YERRA YERRE YERRO YERSI YERTA YERTO YERVO YESAL YESAR YESCA YESON YESOS YETIS YEYES YEYOS YEZGO YINAS YINES YIRAS YIROS YODAD YODAN YODAR YODAS YODEN YODES YODOS YOGAR YOGAS YOGOS YOGUI YOGUR YOLAS YOQUI YORIS YOSES YOYOS YUCAL YUCAS YUCPA YUDOS YUGOS YUMBA YUMBO YUNGA YUNTA YUNTO YURAS YURES YUTAS YUTES YUYAL YUYOS ZABRA ZABRO ZACAS ZACEA ZACEE ZACEO ZADES ZAFAD ZAFAN ZAFAR ZAFAS ZAFEN ZAFES ZAFIA ZAFIO ZAFIR ZAFON ZAFOS ZAFRA ZAFRE ZAGAL ZAGAS ZAGUA ZAHEN ZAHON ZAIDA ZAINA ZAINO ZAJON ZALAS ZALBA ZALBO ZALEA ZALEE ZALEO ZALLA ZALLE ZALLO ZAMBA ZAMBO ZAMPA ZAMPE ZAMPO ZANAS ZANCA ZANCO ZANGA ZANJA ZANJE ZANJO ZAPAD ZAPAN ZAPAR ZAPAS ZAPEA ZAPEE ZAPEN ZAPEO ZAPES ZAQUE ZARBO ZARCA ZARCO ZARES ZARJA ZARPA ZARPE ZARPO ZARZA ZARZO ZATAS ZAYAS ZAZAS ZAZOS ZEBRA ZEDAS ZEGRI ZEINA ZEJEL ZENDA ZENDO ZENES ZENIT ZETAS ZINCS ZOCAD ZOCAN ZOCAR ZOCAS ZOCLO ZOCOS ZOFRA ZOILO ZOIZO ZOLLE ZOMAS ZOMBI ZOMOS ZOMPA ZOMPO ZONAL ZONAS ZONDA ZONTA ZONTO ZONZA ZONZO ZOPAS ZOPES ZOPOS ZOQUE ZORRA ZORRO ZOTAL ZOTES ZOTOL ZUAVO ZUBIA ZUDAS ZUECA ZUECO ZUELA ZUIZA ZULLA ZULLE ZULLO ZULUS ZUMAS ZUMBA ZUMBE ZUMBO ZUMOS ZUNAS ZUNZA ZUÑAN ZUÑAS ZUÑEN ZUÑES ZUÑIA ZUÑID ZUÑIR ZUÑIS ZUÑOS ZUPIA ZURAS ZURBA ZURCE ZURCI ZURDA ZURDE ZURDI ZURDO ZUREA ZUREE ZUREO ZUROS ZURRA ZURRE ZURRI ZURRO ZURZA ZURZO ZUZAR ZUZON";
        Conector cn = Conector.getInstancia();
        cn.connect();
        cn.vertirStringaBD(datos);
        launch();
    }



}
